#!/bin/sh
set -e
. /tmp/scripts/colors

getdep 'openssh'

mkdir -p ~/.ssh
ssh-keygen -t rsa -b 4096 -N '' -f "$HOME/.ssh/id_rsa" || true
echo "/usr/bin/sshd -p 20010 -h \$HOME/.ssh/id_rsa" | sudo tee /usr/bin/startssh && sudo chmod +x /usr/bin/startssh || true
