#!/bin/sh
set -e
. ../../colors

getdep 'xorg-server, xorg-xinit, xf86-video-vesa, xf86-video-fbdev'

echo "${status}   -> ${nc}copying template .xinitrc"
if [ -f "$HOME/.xinitrc" ]; then
	rm "$HOME/.xinitrc"
fi;

cp /etc/X11/xinit/xinitrc $HOME/.xinitrc

echo "${status}   -> ${nc}inserting i3-start into .xinitrc"
# sorry sed syntax for multiline is scary
sed -i "s/twm &//" "$HOME/.xinitrc"
sed -i "s/xterm .\+//" "$HOME/.xinitrc"
sed -i "s/exec/exec i3-start/" "$HOME/.xinitrc"

echo "${status}   -> ${nc}adding touchpad tapping config"
echo 'Section "InputClass"
	Identifier "touchpad"
	Driver "libinput"
	MatchIsTouchpad "on"
	Option "Tapping" "on"
	option "TappingButtonMap" "lmr"
EndSection
' | sudo tee /etc/X11/xorg.conf.d/30-touchpad.conf > /dev/null 2>&1
