#!/bin/sh
set -e

getdep 'xorg-server, xorg-xinit, xf86-video-vesa, xf86-video-fbdev'

if [ -f $HOME/.xinitrc ]; then
	cat $HOME/.xinitrc > $HOME/.xinitrc.backup
	rm $HOME/.xinitrc
fi;

cp /etc/X11/xinit/xinitrc $HOME/.xinitrc

# sorry sed syntax for multiline is scary
sed -i "s/twm &//" $HOME/.xinitrc
sed -i "s/xterm .\+//" $HOME/.xinitrc
sed -i "s/exec/exec i3-start/" $HOME/.xinitrc

echo 'Section "InputClass"
	Identifier "touchpad"
	Driver "libinput"
	MatchIsTouchpad "on"
	Option "Tapping" "on"
	option "TappingButtonMap" "lmr"
EndSection
' | sudo tee /etc/X11/xorg.conf.d/30-touchpad.conf &>/dev/null
