#!/bin/sh
set -e

getdep curl temp
getdep zsh
getdep tmux
getdep rsync

if [ -f "$HOME/.zshrc" ]; then
	cat $HOME/.zshrc > $HOME/.zshrc.beforeinstaller
	rm $HOME/.zshrc
fi;

cp zshrc $HOME/.zshrc
cp lscolors $HOME/.lscolors

if ! [ -d "$HOME/.oh-my-zsh" ]; then
	curl "https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh" -o /tmp/zsh-install.sh
	chmod +x /tmp/zsh-install.sh
	/tmp/zsh-install.sh --unattended --keep-zshrc
else
	echo " -> $HOME/.oh-my-zsh already exists"
fi;
sudo chsh -s /bin/zsh `whoami`

if ! [ -f /usr/share/kbd/consolefonts/ter-powerline-v12n.psf.gz ]; then
	curl "https://raw.githubusercontent.com/powerline/fonts/master/Terminus/PSF/ter-powerline-v12n.psf.gz" | sudo tee /usr/share/kbd/consolefonts/ter-powerline-v12n.psf.gz &>/dev/null
else
	echo " -> /usr/share/kbd/consolefonts/ter-powerline-v12n.psf.gz already exists"
fi;
