#!/bin/sh
set -e

getdep 'kvantum, breeze-icons, breeze-dark-flat, breeze, plasma-workspace'

if [ -d $HOME/.config/Kvantum ]; then
	if [ -d $HOME/.config/KvantumBackup ]; then
		rm -rf $HOME/.config/KvantumBackup
	fi;
	mv $HOME/.config/Kvantum $HOME/.config/KvantumBackup
fi;
cp -r Kvantum $HOME/.config
