#!/bin/sh
set -e

getdep i3-gaps-next-git
getdep i3-volume
getdep i3lock
getdep i3status
getdep python-i3ipc

getdep feh

if [ -d $HOME/.config/i3 ]; then
	if [ -d $HOME/.config/i3-backup ]; then
		rm -rf $HOME/.config/i3-backup
	fi;
	cp -r $HOME/.config/i3 $HOME/.config/i3-backup
fi;
mkdir $HOME/.config/i3 -p
cp -r i3/* $HOME/.config/i3/

cp lb/* $HOME/.local/bin/ || true
mkdir $HOME/.local/share/larbs -p
cp -r larbs/*  $HOME/.local/share/larbs || true
sudo cp ulb/* /usr/local/bin/ || true

cp i3config $HOME/.i3config || true

sudo mkdir -p /usr/share/backgrounds
sudo cp darkbackgrounddesat.png /usr/share/backgrounds/ || true
