#!/bin/sh
set -e
. ../../colors

echo "${status}   -> ${nc}making git directory"
if ! [ -d "$HOME/git/" ]; then
	mkdir "$HOME/git/"
fi;

if ! [ -d "$HOME/git/zsh-syntax-highlighting" ]; then
	echo "${status}   -> ${nc}installing zsh-syntax-highlighting"
	git clone "https://github.com/zsh-users/zsh-syntax-highlighting.git" "$HOME/git/zsh-syntax-highlighting"
else
	echo "${attention}   -> ${nc}$HOME/git/zsh-syntax-highlighting already exists"
fi;

if ! [ -d "$HOME/git/zsh-autocomplete" ]; then
	echo "${status}   -> ${nc}installing zsh-autocomplete"
	git clone "https://github.com/marlonrichert/zsh-autocomplete.git" "$HOME/git/zsh-autocomplete"
else
	echo "${attention}   -> ${nc}$HOME/git/zsh-autocomplete already exists"
fi;

if ! [ -d "$HOME/.oh-my-zsh/custom/themes/powerlevel10k" ]; then
	echo "${status}   -> ${nc}installing powerlevel10k"
	git clone --depth=1 "https://github.com/romkatv/powerlevel10k.git" "$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
else
	echo "${attention}   -> ${nc}$HOME/.oh-my-zsh/custom/themes/powerlevel10k already exists"
fi;

if ! [ -d "$HOME/.oh-my-zsh/custom/plugins/vi-mode" ]; then
	echo "${status}   -> ${nc}installing vi-mode"
	git clone "https://github.com/Nyquase/vi-mode" "$HOME/.oh-my-zsh/custom/plugins/vi-mode"
else
	echo "${attention}   -> ${nc}$HOME/.oh-my-zsh/custom/plugins/vi-mode already exists"
fi;

if ! [ -d "$HOME/.oh-my-zsh/custom/plugins/zsh-vimode-visual" ]; then
	echo "${status}   -> ${nc}installing zsh-vimode-visual"
	git clone "https://github.com/b4b4r07/zsh-vimode-visual" "$HOME/.oh-my-zsh/custom/plugins/zsh-vimode-visual"
else
	echo "${attention}   -> ${nc}$HOME/.oh-my-zsh/custom/plugins/zsh-vimode-visual already exists"
fi;


echo "${status}   -> ${nc}copying .p10k.zsh"
if [ -f "$HOME/.p10k.zsh" ]; then
	rm "$HOME/.p10k.zsh"
fi;
cp p10k.zsh "$HOME/.p10k.zsh"

echo "${status}   -> ${nc}copying .p10k.tty.zsh"
if [ -f "$HOME/.p10k.tty.zsh" ]; then
	rm "$HOME/.p10k.tty.zsh"
fi;
cp p10k.tty.zsh "$HOME/.p10k.tty.zsh"
