#!/bin/sh
set -e
. ../../colors

echo "${status}   -> ${nc}adding PLATFORMTHEME to /etc/environment"
echo "$(cat /etc/environment)
QT_QPA_PLATFORMTHEME=qt5ct" | sudo tee /etc/environment >/dev/null

echo "${status}   -> ${nc}backing up /etc/pacman.conf"
sudo cp /etc/pacman.conf /etc/pacman.backup || true
echo "${status}   -> ${nc}updating /etc/pacman.conf"
sudo sed -i "s/#Color/Color/" /etc/pacman.conf
sudo sed -i "s/#ParallelDownloads.\+/ParallelDownloads = 5\nILoveCandy/" /etc/pacman.conf

getdep 'noto-fonts, noto-fonts-emoji, nerd-fonts-fira-code, qt5ct, btop, openssh, ntfs-3g'

