#!/bin/sh
set -e
. /tmp/scripts/colors

getdep 'powerline, python-psutil, xorg-xrandr'

echo "${status}   -> ${nc}copying powerline configs"
if [ -d "$HOME/.config/powerline" ]; then
	rm -rf "$HOME/.config/powerline"
fi;

cp -r powerline "$HOME/.config/"

echo "${status}   -> ${nc}copying custom powerline segments"
if [ -d "$HOME/.config/powerline-segments" ]; then
	rm -rf "$HOME/.config/powerline-segments"
fi;

cp -r powerline-segments "$HOME/.config/"

echo "${status}   -> ${nc}symlinking custom powerline segments"
sudo ln -sf "$HOME/.config/powerline-segments/*.py" "/usr/lib/python3.10/site-packages/powerline/segments/common/"
