#!/bin/sh
escape='\033['
red=${escape}0\;31m
cyan=${escape}0\;36m
blue=${escape}1\;34m
gold=${escape}1\;33m
green=${escape}1\;32m

done=$blue
error=$red
status=$blue
interact=$green
attention=$cyan
nc=${escape}0m

alias echo='echo -e'
