#!/bin/sh
escape='\033['
export red=${escape}0\;31m
export cyan=${escape}0\;36m
export blue=${escape}1\;34m
export gold=${escape}1\;33m
export green=${escape}1\;32m

export done=$blue
export error=$red
export status=$blue
export interact=$green
export attention=$gold
export nc=${escape}0m

alias echo='echo -e'
