#!/bin/sh
set -e

getdep dunst
getdep libnotify

if [ -d $HOME/.config/dunst ]; then
	if [ -d $HOME/.config/dunst-backup ]; then
		rm -rf $HOME/.config/dunst-backup
	fi;
	mkdir -p $HOME/.config/dunst-backup
	mv $HOME/.config/dunst/* $HOME/.config/dunst-backup/
fi;

mkdir $HOME/.config/dunst -p
cp dunstrc $HOME/.config/dunst
