#!/bin/sh
set -e

if ! [ -d "$HOME/git/" ]; then
	mkdir "$HOME/git/"
fi;

getdep git

where=`pwd`
cd "$HOME/git/"

if [ -d $HOME/git/yay ]; then
	alreadyexists=1
fi;

if [ -z $alreadyexists ]; then
	echo " -> git cloning yay"
	git clone https://aur.archlinux.org/yay.git
	cd yay
	makepkg -si
	cd $where
	rm -rf "$HOME/git/yay"
else
	echo " -> installing yay"
	cd yay
	makepkg -si
	cd $where
fi;
