#!/bin/sh
set -e

getdep picom-ibhagwan-git

if [ -f $HOME/.config/picom.conf ]; then
	cat $HOME/.config/picom.conf > $HOME/.config/picom.conf.backup
	rm $HOME/.config/picom.conf
fi;

cp picom.conf $HOME/.config
