#!/bin/sh
set -e
. ../../colors

getdep picom-ibhagwan-git

echo "${status}   -> ${nc}copying Picom configs"
if [ -f "$HOME/.config/picom.conf" ]; then
	cat "$HOME/.config/picom.conf" > "$HOME/.config/picom.conf.backup"
	rm "$HOME/.config/picom.conf"
fi;

cp picom.conf "$HOME/.config"
